name: Deploy Release
on:
  release:
    types: [published]
env:
  TF_VAR_region: us-central1
  TF_VAR_zone: us-central1-c
  TF_VAR_prodProjectId: 'dc-thrush-prod'
  TF_VAR_coreProjectId: 'dc-thrush-core'
jobs:
  deploy-gcp:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/main/
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_KEY }}'
          create_credentials_file: true
          export_environment_variables: true
      - run: terraform init
      - run: terraform apply -auto-approve -lock-timeout=60s -input=false -backup=-
  deploy-k8s:
    runs-on: ubuntu-latest
    needs: deploy-gcp
    defaults:
      run:
        working-directory: ./k8s
    steps:
      - uses: actions/checkout@v2
      - name: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_KEY }}'
      - name: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v0'
        with:
          cluster_name: 'dc-thrush-prod'
          location: ${{ env.TF_VAR_region }}
          project_id: ${{ env.TF_VAR_projectId }}
      - uses: imranismail/setup-kustomize@v1
      - run: |
          kubectl config set-context --current --namespace infra
          kustomize build ./infra --enable-helm | kubectl apply -f -
